services:
  build:
    build:
      context: ../..
      dockerfile: ./dockerfiles/wasm/Dockerfile
    volumes:
      - type: bind
        source: ../../target
        target: /app/target
      - type: bind
        source: ../../crates
        target: /app/crates
      - type: bind
        source: ../../npm
        target: /app/npm
      - type: bind
        source: ./additional
        target: /app/additional
    working_dir: /app
    command: ["wasm-pack", "build", "npm", "--target=web"]
