services:
  build:
    build:
      context: ../..
      dockerfile: ./dockerfiles/wasm/Dockerfile
    volumes:
      - type: bind
        source: ../../target
        target: /app/target
      - type: bind
        source: ../../crates
        target: /app/crates
      - type: bind
        source: ../../npm
        target: /app/npm
      - type: bind
        source: ./emcc.sh
        target: /app/emcc.sh
      - type: bind
        source: ./em++.sh
        target: /app/em++.sh
    working_dir: /app
    command: ["wasm-pack", "build", "npm", "--target=web"]
