use libraw_sys as sys;
#[allow(non_camel_case_types)]
#[derive(Debug, PartialEq)]
pub enum CameraMount {
    Unknown(u32),
    Alpa,
    C,
    Canon_EF_M,
    Canon_EF_S,
    Canon_EF,
    Canon_RF,
    Contax_N,
    Contax645,
    FT,
    mFT,
    Fuji_GF,
    Fuji_GX,
    Fuji_X,
    Hasselblad_H,
    Hasselblad_V,
    Hasselblad_XCD,
    Leica_M,
    Leica_R,
    Leica_S,
    Leica_SL,
    Leica_TL,
    LPS_L,
    Mamiya67,
    Mamiya645,
    Minolta_A,
    Nikon_CX,
    Nikon_F,
    Nikon_Z,
    PhaseOne_iXM_MV,
    PhaseOne_iXM_RS,
    PhaseOne_iXM,
    Pentax_645,
    Pentax_K,
    Pentax_Q,
    RicohModule,
    Rollei_bayonet,
    Samsung_NX_M,
    Samsung_NX,
    Sigma_X3F,
    Sony_E,
    LF,
    DigitalBack,
    FixedLens,
    IL_UM,
    TheLastOne,
}
impl From<u32> for CameraMount {
    fn from(value: u32) -> Self {
        match value {
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Alpa => CameraMount::Alpa,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_C => CameraMount::C,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Canon_EF_M => CameraMount::Canon_EF_M,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Canon_EF_S => CameraMount::Canon_EF_S,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Canon_EF => CameraMount::Canon_EF,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Canon_RF => CameraMount::Canon_RF,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Contax_N => CameraMount::Contax_N,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Contax645 => CameraMount::Contax645,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_FT => CameraMount::FT,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_mFT => CameraMount::mFT,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Fuji_GF => CameraMount::Fuji_GF,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Fuji_GX => CameraMount::Fuji_GX,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Fuji_X => CameraMount::Fuji_X,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Hasselblad_H => CameraMount::Hasselblad_H,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Hasselblad_V => CameraMount::Hasselblad_V,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Hasselblad_XCD => CameraMount::Hasselblad_XCD,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Leica_M => CameraMount::Leica_M,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Leica_R => CameraMount::Leica_R,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Leica_S => CameraMount::Leica_S,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Leica_SL => CameraMount::Leica_SL,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Leica_TL => CameraMount::Leica_TL,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_LPS_L => CameraMount::LPS_L,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Mamiya67 => CameraMount::Mamiya67,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Mamiya645 => CameraMount::Mamiya645,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Minolta_A => CameraMount::Minolta_A,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Nikon_CX => CameraMount::Nikon_CX,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Nikon_F => CameraMount::Nikon_F,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Nikon_Z => CameraMount::Nikon_Z,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_PhaseOne_iXM_MV => CameraMount::PhaseOne_iXM_MV,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_PhaseOne_iXM_RS => CameraMount::PhaseOne_iXM_RS,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_PhaseOne_iXM => CameraMount::PhaseOne_iXM,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Pentax_645 => CameraMount::Pentax_645,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Pentax_K => CameraMount::Pentax_K,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Pentax_Q => CameraMount::Pentax_Q,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_RicohModule => CameraMount::RicohModule,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Rollei_bayonet => CameraMount::Rollei_bayonet,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Samsung_NX_M => CameraMount::Samsung_NX_M,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Samsung_NX => CameraMount::Samsung_NX,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Sigma_X3F => CameraMount::Sigma_X3F,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_Sony_E => CameraMount::Sony_E,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_LF => CameraMount::LF,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_DigitalBack => CameraMount::DigitalBack,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_FixedLens => CameraMount::FixedLens,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_IL_UM => CameraMount::IL_UM,
            sys::LibRaw_camera_mounts_LIBRAW_MOUNT_TheLastOne => CameraMount::TheLastOne,
            _ => CameraMount::Unknown(value),
        }
    }
}
