name: Setup environment
description: Setup environment for the project

inputs:
  node-version:
    description: Node.js version
    default: lts/*

runs:
  using: 'composite'
  steps:
    - uses: dtolnay/rust-toolchain@stable
      with:
        compnents: rustfmt, clippy
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
    - run: pnpm install
      shell: bash
