services:
  build:
    build:
      context: ../..
      dockerfile: ./dockerfiles/wasi/Dockerfile
    volumes:
      - type: bind
        source: ../../target
        target: /app/target
      - type: bind
        source: ../../crates
        target: /app/crates
      - type: bind
        source: ../../npm
        target: /app/npm
      - type: bind
        source: ../../.cargo
        target: /app/.cargo
    working_dir: /app
    command: ["pnpm", "napi", "build", "--release", "-o", "dist", "--cwd", "./npm", "--package", "libraw-rs-wasm", "--target", "wasm32-wasip1-threads", "--platform"]
    environment:
      - RUSTFLAGS=-L/opt/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasip1-threads
