[package]
name = "libraw-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
libraw-rs-sys = { git = "https://github.com/paolobarbolini/libraw-rs.git", rev = "9e28687ce279c34f82622d98bd673e8ea8964d89" }
