name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
      - run: cargo test
      - if: matrix.os == 'ubuntu-latest'
        run: cargo clippy && cargo fmt --check

  build-wasi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-wasi-sdk
      - uses: ./.github/actions/setup
      - run: rustup target add wasm32-wasip1-threads
      - run: pnpm napi build --release --cwd ./npm --package libraw-rs-wasm --target wasm32-wasip1-threads --platform
